spring.application.name=core
phantombuster.api-key=
phantombuster.base-url=
linked-in.cookie=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=300000

spring.datasource.username=
spring.datasource.password=
spring.datasource.url=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false