spring.application.name=core
phantombuster.api-key=ExAjpUvxIq349yGjkmaP7y6MR7GgvODqODolXEgKLdI
phantombuster.base-url=https://api.phantombuster.com/api/v2
linked-in.cookie=AQEDAUcMy-IAzb_tAAABm-sMBbAAAAGcb_w7B00An9oGJmnYths67kDbAwgCzC3s_HGlA9BT7l43CcWyTRqNu8RHwhQYTYPvYKpoIFmCto4A5mf3NCnaYq9Ezi-lDguV_3-EEGn1D7I7bVISPpDfA3kg

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Xs6xMcu5NtCL
spring.datasource.url=jdbc:postgresql://ep-dry-flower-a103ueht-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false